version: "3.9"

services:
  db:
    image: postgres:14
    container_name: "bank-db"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5433:5432'
    # volumes:
    #   - var/run/postgresql:var/run/postgresql

